# Generated by Django 6.0.7 on 2026-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_hookup_accepted',
            field=models.BooleanField(default=False, help_text='True if the girl accepted the request'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_hookup_request',
            field=models.BooleanField(default=False, help_text='True if this message is a specific meetup request'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Female users toggle this to signal hookup availability'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Male users must be True to send messages'),
        ),
    ]
