# Generated by Django 6.0.7 on 2026-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_is_hookup_accepted_message_is_hookup_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
