# Generated by Django 6.0.7 on 2026-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this message will permanently disappear', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_hookup_accepted',
            field=models.BooleanField(default=False, help_text='True if the request was accepted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_hookup_request',
            field=models.BooleanField(default=False, help_text='True if this is a meetup request'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Toggle to signal availability'),
        ),
    ]
