# Generated by Django 6.0.7 on 2026-07-18 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_expires_at_alter_message_is_hookup_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeMeetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('meeting_time', models.DateTimeField()),
                ('expected_duration', models.IntegerField(default=2, help_text='Expected duration in hours')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('share_location', models.BooleanField(default=True, help_text='Share real-time location with emergency contact')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed Safely'), ('emergency', 'Emergency Triggered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_due', models.DateTimeField(blank=True, help_text='When the safety check-in is expected', null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_location', models.CharField(blank=True, help_text='Location during check-in', max_length=300)),
                ('emergency_triggered', models.BooleanField(default=False)),
                ('emergency_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('swipe', 'Swipe'), ('match', 'Match'), ('message', 'Message'), ('hookup_request', 'Hookup Request'), ('report', 'Report'), ('block', 'Block'), ('profile_update', 'Profile Update'), ('photo_upload', 'Photo Upload'), ('safety_check', 'Safety Check-in')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the activity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, help_text='mobile, desktop, tablet', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('photo', 'Photo Verification'), ('id', 'ID Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='verifications/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='blockreport',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details for reports'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False, help_text='System-generated messages (safety, etc.)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hookup_requests_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hookup_requests_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='incognito_mode',
            field=models.BooleanField(default=False, help_text='Hide from feeds until you swipe first'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interest tags'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='safety_score',
            field=models.IntegerField(default=100, help_text='Safety reputation score (0-100)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_distance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_swipes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_level',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('email_verified', 'Email Verified'), ('photo_verified', 'Photo Verified'), ('id_verified', 'ID Verified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockreport',
            name='reason',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('fake_profile', 'Fake Profile'), ('inappropriate_content', 'Inappropriate Content'), ('spam', 'Spam/Scam'), ('safety_concern', 'Safety Concern'), ('auto_block_from_report', 'Auto-blocked from Report'), ('user_block', 'User Block'), ('other', 'Other')], default='user_block', max_length=50),
        ),
        migrations.AlterField(
            model_name='blockreport',
            name='type',
            field=models.CharField(choices=[('block', 'Block'), ('report', 'Report')], default='block', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='blockreport',
            index=models.Index(fields=['type', '-created_at'], name='core_blockr_type_501025_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_available', '-last_active'], name='core_profil_is_avai_549bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'is_available'], name='core_profil_gender_0b6dde_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['safety_score'], name='core_profil_safety__a1f2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['verification_level'], name='core_profil_verific_d4a147_idx'),
        ),
        migrations.AddField(
            model_name='safemeetrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_meets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safemeetrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safemeet_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safemeetrequest',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_meets', to='core.match'),
        ),
        migrations.AddField(
            model_name='safemeetrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safemeet_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.match'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='safemeetrequest',
            index=models.Index(fields=['status', 'meeting_time'], name='core_safeme_status_79d8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='safemeetrequest',
            index=models.Index(fields=['from_user', 'to_user'], name='core_safeme_from_us_f20e25_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_efaa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', '-timestamp'], name='core_userac_activit_698061_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address'], name='core_userac_ip_addr_9ed689_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userverification',
            unique_together={('user', 'verification_type')},
        ),
    ]
